language: java
notifications:
  hipchat:
    rooms:
      secure: vK4psqRXR1VGp2k5Y64T1NG2Vlbd5G1lGuGXfNWlCy61oyk5qf7QUCVhXY50Wl9Hu4AS+DpZpAL70ADZkLccYzF3HFFGrP6zu8tzIbWYx0ldvfnVsWY91lldQvsVOdblL3XePwuTdXeRxTB/0FFbuqbPelfUoj78JbZF6E8udf1pQQuPFE4o5j7sADIlh1SECW29j6IAl+isN6v6dG7GkZYZZEC89vmwBx/NqhSuWdFC1pztgjNjG5XNLpqKP/373F7WN21aJux11vNU2De1QICINBb3NTGowwf3fnfIcyA7FOkyIa1s6lZC8D8BEozUIBncE2W6N9+wq5wMGZlYNH8I7WqvJCffkb2sQnsCsILeUrAedITzHDnJ7173QiyXtUSulvKFNFTda14JSJjAM2zOrd7hIYMNeup9wLU8jN//8H0b4A5apaNEKFlk5sIY1lIMzuUjXrLjxVe8T7rNy6ht0m6o6P5DQ61j0pt/UT8KemAPW/K4AzwXDUAT9QunRHrn+/9V4N/WpRm/DN2WIFXu/sug/KI5e2Fx1Cz2RooufU1EDfbkA6lSiAWXxS8No2Hg5wIC8Ljry33Yg8zAig1LkAd4q3PD8iTMAnj5pPVXYVoEccFRUzWe3Um3+DyMZfilhMZmmyecU4INh15gAG+fC6fXZbI1RtzztK5MyBM=
deploy:
  provider: releases
  api_key:
    secure: JdUychBhKe5CdOkhQdBooNDWFMYCFIvXffTio5PwnWTSkCY/gGngK0Tc1e6aSLYRQWHKVYgtQn3m70qMlJ1az6Zcuu4z0nzT0XzP8fY2ojgx/cLw0/ygwFc1AXBZqc2hTWFeTrtKI+xbRhv2AYLg/sFJx0Eb+QYV0Zwydx0B2VYXVt8SxSKHiCsBRwWUMtaYNk7HPzZFCkN8S4xXuC/0dxpGcI1ota4CN53k7sYq1ueWKhgGYMHPvycP5tvtSx7gPuI5KnQp2K+KSGhDd/fw378iWKfuXKcH6y8/jmvjHyDGmoiyIwDGL9V0Jh/ZNyvHaQOrK2W24rj0/9E8ihj/htKKJF7sr+6q5rZilyZyMBaB3zwgaqm60ORgjr7JnldZRu5oUQrhWuxWXdwIfQoep5RVQf5qttGOBBjxqjxXuMyREWA6PxB23Wl9aMYZ+IAS1ca8POB2cx+u8Nd0QaOv3Zsh9fSrKc5ESGYmxoli3ZQn6DhyyaBGURV6kRUNzjTy86pRhp8HhSI6tZ+UTATtam7KB5KnfGMaNFplgbwo9oTINylT8j9uBAvIzJpBzZX5hensgVyGyxjFhd2ugh1H1+sCigGXk1IOtvQ84br8K1iWExxI4qQvHMHPXPDPdfrxwqtwlWElO83oKmGKk0Q43m/22aUFyYoE404FIWQoQiY=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-pega-plugin
