language: java
notifications:
  hipchat:
    rooms:
      secure: vK4psqRXR1VGp2k5Y64T1NG2Vlbd5G1lGuGXfNWlCy61oyk5qf7QUCVhXY50Wl9Hu4AS+DpZpAL70ADZkLccYzF3HFFGrP6zu8tzIbWYx0ldvfnVsWY91lldQvsVOdblL3XePwuTdXeRxTB/0FFbuqbPelfUoj78JbZF6E8udf1pQQuPFE4o5j7sADIlh1SECW29j6IAl+isN6v6dG7GkZYZZEC89vmwBx/NqhSuWdFC1pztgjNjG5XNLpqKP/373F7WN21aJux11vNU2De1QICINBb3NTGowwf3fnfIcyA7FOkyIa1s6lZC8D8BEozUIBncE2W6N9+wq5wMGZlYNH8I7WqvJCffkb2sQnsCsILeUrAedITzHDnJ7173QiyXtUSulvKFNFTda14JSJjAM2zOrd7hIYMNeup9wLU8jN//8H0b4A5apaNEKFlk5sIY1lIMzuUjXrLjxVe8T7rNy6ht0m6o6P5DQ61j0pt/UT8KemAPW/K4AzwXDUAT9QunRHrn+/9V4N/WpRm/DN2WIFXu/sug/KI5e2Fx1Cz2RooufU1EDfbkA6lSiAWXxS8No2Hg5wIC8Ljry33Yg8zAig1LkAd4q3PD8iTMAnj5pPVXYVoEccFRUzWe3Um3+DyMZfilhMZmmyecU4INh15gAG+fC6fXZbI1RtzztK5MyBM=
deploy:
  provider: releases
  api_key:
    secure: q2jpgrNjuthMlZc0wVOsw2Il0vQlzz0vkx0qHq6JVHxFSytkqZK1rF+P+yAG0xe5YhYjB4ATYaURqX031ubjXrhLFGpwkh7VroSX65CGzWICIA8GDB1Va8JteBWHnEuag413fT6r7ZB/J/GlRAo3l1+Tgr0ZfSp+1Mu+bIGywze69gtWjo/0EJUlSaCIe4y/RrPEqQoEjazt2lmPAdbnTXW3+8GtRDjte1T/yJhorsi0QnuFZEN+ICLZ64wp3JkbKDDSBrt/NmXN/i517mhlGw3BZ/W3Fm1UC+g6BVowlfaqYyL5c2rcliZzTdOBWB2kORXCsBtGQWO6jxsycdSlgnQGLRjTStcCYCjG3mC6A6MNZogw0j9RIuEWr5yLOzMoBO3s13quCHXgOQm219qTuz1fr9dEuXILxKbCATt8Zetxr4yz7JX+HPXKMh7ZZoMl7e46qKdLtxZqJt87B9P8m8gtuXnwWWobxHqV//QAwee7d5/idTZdgi9TklnQKK/dCs2Krzm5YDWun6eagg0MbkslNDpYixaWeVFSiBs8LqXYBLNEGYdv2XgOYUGtFV1d2l+JsdBHTRLHFkrP1s6kcHGJuVlq/lgycq86XSwbCuJBZRN9xH0XNVrGNedsS8Dvy3IsmT5fPVY1zZWSwA6vbLn3c74I4fz3pf7YSoKQ2YU=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-pega-plugin
